#ifndef _PUD_H_
#define _PUD_H_

typedef enum
{
   PUD_SECTION_TYPE     = 0,
   PUD_SECTION_VER      = 1,
   PUD_SECTION_DESC     = 2,
   PUD_SECTION_OWNR     = 3,
   PUD_SECTION_ERA      = 4,
   PUD_SECTION_ERAX     = 5,
   PUD_SECTION_DIM      = 6,
   PUD_SECTION_UDTA     = 7,
   PUD_SECTION_ALOW     = 8,
   PUD_SECTION_UGRD     = 9,
   PUD_SECTION_SIDE     = 10,
   PUD_SECTION_SGLD     = 11,
   PUD_SECTION_SLBR     = 12,
   PUD_SECTION_SOIL     = 13,
   PUD_SECTION_AIPL     = 14,
   PUD_SECTION_MTXM     = 15,
   PUD_SECTION_SQM      = 16,
   PUD_SECTION_OILM     = 17,
   PUD_SECTION_REGM     = 18,
   PUD_SECTION_UNIT     = 19
} Pud_Section;

typedef enum
{
   PUD_DIMENSIONS_UNDEFINED = 0,
   PUD_DIMENSIONS_32_32,
   PUD_DIMENSIONS_64_64,
   PUD_DIMENSIONS_96_96,
   PUD_DIMENSIONS_128_128
} Pud_Dimensions;

typedef enum
{
   PUD_UPGRADE_SWORD_1          = 0,
   PUD_UPGRADE_SWORD_2,
   PUD_UPGRADE_AXE_1,
   PUD_UPGRADE_AXE_2,
   PUD_UPGRADE_ARROW_1,
   PUD_UPGRADE_ARROW_2,
   PUD_UPGRADE_SPEAR_1,
   PUD_UPGRADE_SPEAR_2,
   PUD_UPGRADE_HUMAN_SHIELD_1,
   PUD_UPGRADE_HUMAN_SHIELD_2,
   PUD_UPGRADE_ORC_SHIELD_1,
   PUD_UPGRADE_ORC_SHIELD_2,
   PUD_UPGRADE_HUMAN_SHIP_CANNON_1,
   PUD_UPGRADE_HUMAN_SHIP_CANNON_2,
   PUD_UPGRADE_ORC_SHIP_CANNON_1,
   PUD_UPGRADE_ORC_SHIP_CANNON_2,
   PUD_UPGRADE_HUMAN_SHIP_ARMOR_1,
   PUD_UPGRADE_HUMAN_SHIP_ARMOR_2,
   PUD_UPGRADE_ORC_SHIP_ARMOR_1,
   PUD_UPGRADE_ORC_SHIP_ARMOR_2,
   PUD_UPGRADE_CATAPULT_1,
   PUD_UPGRADE_CATAPULT_2,
   PUD_UPGRADE_BALLISTA_1,
   PUD_UPGRADE_BALLISTA_2,
   PUD_UPGRADE_TRAIN_RANGERS,
   PUD_UPGRADE_LONGBOW,
   PUD_UPGRADE_RANGER_SCOUTING,
   PUD_UPGRADE_RANGER_MARKSMANSHIP,
   PUD_UPGRADE_TRAIN_BERSERKERS,
   PUD_UPGRADE_LIGHTER_AXES,
   PUD_UPGRADE_BERSERKER_SCOUTING,
   PUD_UPGRADE_BERSERKER_REGENERATION,
   PUD_UPGRADE_TRAIN_OGRE_MAGES,
   PUD_UPGRADE_TRAIN_PALADINS,
   PUD_UPGRADE_HOLY_VISION,
   PUD_UPGRADE_HEALING,
   PUD_UPGRADE_EXORCISM,
   PUD_UPGRADE_FLAME_SHIELD,
   PUD_UPGRADE_FIREBALL,
   PUD_UPGRADE_SLOW,
   PUD_UPGRADE_INVISIBILITY,
   PUD_UPGRADE_POLYMORPH,
   PUD_UPGRADE_BLIZZARD,
   PUD_UPGRADE_EYE_OF_KILROGG,
   PUD_UPGRADE_BLOODLUST,
   PUD_UPGRADE_RAISE_DEAD,
   PUD_UPGRADE_DEATH_COIL,
   PUD_UPGRADE_WHIRLWIND,
   PUD_UPGRADE_HASTE,
   PUD_UPGRADE_UNHOLY_ARMOR,
   PUD_UPGRADE_RUNES,
   PUD_UPGRADE_DEATH_AND_DECAY
} Pud_Upgrade;

typedef enum
{
   PUD_UNIT_INFANTRY,
   PUD_UNIT_GRUNT,
   PUD_UNIT_PEASANT,
   PUD_UNIT_PEON,
   PUD_UNIT_BALLISTA,
   PUD_UNIT_CATAPULT,
   PUD_UNIT_KNIGHT,
   PUD_UNIT_OGRE,
   PUD_UNIT_ARCHER,
   PUD_UNIT_AXETHROWER,
   PUD_UNIT_MAGE,
   PUD_UNIT_DEATH_KNIGHT,
   PUD_UNIT_PALADIN,
   PUD_UNIT_OGRE_MAGE,
   PUD_UNIT_DWARVES,
   PUD_UNIT_GOBLIN_SAPPER,
   PUD_UNIT_ATTACK_PEASANT,
   PUD_UNIT_ATTACK_PEON,
   PUD_UNIT_RANGER,
   PUD_UNIT_BERSERKER,
   PUD_UNIT_ALLERIA,
   PUD_UNIT_TERON_GOREFIEND,
   PUD_UNIT_KURDAN_AND_SKY_REE,
   PUD_UNIT_DENTARG,
   PUD_UNIT_KHADGAR,
   PUD_UNIT_GROM_HELLSCREAM,
   PUD_UNIT_HUMAN_TANKER,
   PUD_UNIT_ORC_TANKER,
   PUD_UNIT_HUMAN_TRANSPORT,
   PUD_UNIT_ORC_TRANSPORT,
   PUD_UNIT_ELVEN_DESTROYER,
   PUD_UNIT_TROLL_DESTROYER,
   PUD_UNIT_BATTLESHIP,
   PUD_UNIT_JUGGERNAUGHT,
   PUD_UNIT_DEATHWING,
   PUD_UNIT_GNOMISH_SUBMARINE,
   PUD_UNIT_GIANT_TURTLE,
   PUD_UNIT_GNOMISH_FLYING_MACHINE,
   PUD_UNIT_GOBLIN_ZEPPLIN,
   PUD_UNIT_GRYPHON_RIDER,
   PUD_UNIT_DRAGON,
   PUD_UNIT_TURALYON,
   PUD_UNIT_EYE_OF_KILROGG,
   PUD_UNIT_DANATH,
   PUD_UNIT_KHORGATH_BLADEFIST,
   PUD_UNIT_CHO_GALL,
   PUD_UNIT_LOTHAR,
   PUD_UNIT_GUL_DAN,
   PUD_UNIT_UTHER_LIGHTBRINGER,
   PUD_UNIT_ZULJIN,
   PUD_UNIT_SKELETON,
   PUD_UNIT_DAEMON,
   PUD_UNIT_CRITTER,
   PUD_UNIT_FARM,
   PUD_UNIT_PIG_FARM,
   PUD_UNIT_HUMAN_BARRACKS,
   PUD_UNIT_ORC_BARRACKS,
   PUD_UNIT_CHURCH,
   PUD_UNIT_ALTAR_OF_STORMS,
   PUD_UNIT_HUMAN_SCOUT_TOWER,
   PUD_UNIT_ORC_SCOUT_TOWER,
   PUD_UNIT_STABLES,
   PUD_UNIT_OGRE_MOUND,
   PUD_UNIT_GNOMISH_INVENTOR,
   PUD_UNIT_GOBLIN_ALCHEMIST,
   PUD_UNIT_GRYPHON_AVIARY,
   PUD_UNIT_DRAGON_ROOST,
   PUD_UNIT_HUMAN_SHIPYARD,
   PUD_UNIT_ORC_SHIPYARD,
   PUD_UNIT_TOWN_HALL,
   PUD_UNIT_GREAT_HALL,
   PUD_UNIT_ELVEN_LUMBER_MILL,
   PUD_UNIT_TROLL_LUMBER_MILL,
   PUD_UNIT_HUMAN_FOUNDRY,
   PUD_UNIT_ORC_FOUNDRY,
   PUD_UNIT_MAGE_TOWER,
   PUD_UNIT_TEMPLE_OF_THE_DAMNED,
   PUD_UNIT_HUMAN_BLACKSMITH,
   PUD_UNIT_ORC_BLACKSMITH,
   PUD_UNIT_HUMAN_REFINERY,
   PUD_UNIT_ORC_REFINERY,
   PUD_UNIT_HUMAN_OIL_WELL,
   PUD_UNIT_ORC_OIL_WELL,
   PUD_UNIT_KEEP,
   PUD_UNIT_STRONGHOLD,
   PUD_UNIT_CASTLE,
   PUD_UNIT_FORTRESS,
   PUD_UNIT_GOLD_MINE,
   PUD_UNIT_OIL_PATCH,
   PUD_UNIT_HUMAN_START,
   PUD_UNIT_ORC_START,
   PUD_UNIT_HUMAN_GUARD_TOWER,
   PUD_UNIT_ORC_GUARD_TOWER,
   PUD_UNIT_HUMAN_CANNON_TOWER,
   PUD_UNIT_ORC_CANNON_TOWER,
   PUD_UNIT_CIRCLE_OF_POWER,
   PUD_UNIT_DARK_PORTAL,
   PUD_UNIT_RUNESTONE,
   PUD_UNIT_HUMAN_WALL,
   PUD_UNIT_ORC_WALL
} Pud_Unit;

typedef enum
{
   PUD_ERA_FOREST,
   PUD_ERA_WINTER,
   PUD_ERA_WASTELAND,
   PUD_ERA_SWAMP
} Pud_Era;

typedef struct _Pud Pud;


Pud *pud_new(const char *file);
void pud_free(Pud *pud);
int pud_parse(Pud *pud);
void pud_verbose_set(Pud *pud, int on);
bool pud_section_is_optional(Pud_Section sec);
uint32_t pud_go_to_section(Pud *pud, Pud_Section sec);
void pud_print(Pud *pud, FILE *stream);
void pud_dimensions_to_size(Pud_Dimensions dim, int *x_ret, int *y_ret);

bool pud_parse_type(Pud *pud);
bool pud_parse_ver(Pud *pud);
bool pud_parse_desc(Pud *pud);
bool pud_parse_era(Pud *pud);
bool pud_parse_dim(Pud *pud);
bool pud_parse_udta(Pud *pud);
bool pud_parse_alow(Pud *pud);
bool pud_parse_ugrd(Pud *pud);
bool pud_parse_ugrd(Pud *pud);
bool pud_parse_sgld(Pud *pud);
bool pud_parse_slbr(Pud *pud);
bool pud_parse_soil(Pud *pud);
bool pud_parse_mtxm(Pud *pud);
bool pud_parse_oilm(Pud *pud);
bool pud_parse_regm(Pud *pud);
bool pud_parse_unit(Pud *pud);


bool pud_minimap_to_ppm(Pud *pud, const char *file);
bool pud_minimap_to_jpeg(Pud *pud, const char *file);


#endif /* ! _PUD_H_ */

